import { ElementInfo, ElementType } from "@/types/elements";

export const ELEMENTS: Record<ElementType, ElementInfo> = {
  wood: {
    id: "wood",
    nameKo: "목(木)",
    nameEn: "Wood",
    hanja: "木",
    color: "#22c55e",
    bgColor: "bg-green-50",
    borderColor: "border-green-300",
    description:
      "목(木)형은 나무처럼 곧고 길게 뻗는 형상을 지닙니다. 얼굴이 길고 직사각형에 가까우며, 이마가 높고 턱선이 두드러집니다. 성장과 발전의 기운을 품고 있어 진취적이고 창의적인 성향을 가집니다.",
    faceCharacteristics: [
      "길고 직사각형에 가까운 얼굴형",
      "높고 넓은 이마",
      "두드러진 턱선과 각진 턱",
      "갸름하고 긴 인상",
      "뚜렷한 이목구비",
    ],
    personalityTraits: [
      "진취적이고 도전적",
      "창의력이 뛰어남",
      "리더십이 강함",
      "인내심과 끈기가 있음",
      "정의감이 강함",
    ],
    season: "봄",
    direction: "동",
    organ: "간(肝)",
  },
  fire: {
    id: "fire",
    nameKo: "화(火)",
    nameEn: "Fire",
    hanja: "火",
    color: "#ef4444",
    bgColor: "bg-red-50",
    borderColor: "border-red-300",
    description:
      "화(火)형은 불꽃처럼 위로 타오르는 형상을 지닙니다. 역삼각형 또는 하트형 얼굴로 이마가 넓고 턱이 뾰족합니다. 열정과 활력의 기운이 넘쳐 표현력이 풍부하고 사교적인 성향을 가집니다.",
    faceCharacteristics: [
      "역삼각형 또는 하트형 얼굴",
      "넓은 이마",
      "뾰족하고 좁은 턱",
      "날카로운 이목구비",
      "밝고 빛나는 눈",
    ],
    personalityTraits: [
      "열정적이고 활기참",
      "표현력이 풍부함",
      "사교적이고 매력적",
      "직관력이 뛰어남",
      "낙관적인 성격",
    ],
    season: "여름",
    direction: "남",
    organ: "심(心)",
  },
  earth: {
    id: "earth",
    nameKo: "토(土)",
    nameEn: "Earth",
    hanja: "土",
    color: "#eab308",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-300",
    description:
      "토(土)형은 대지처럼 안정되고 넓은 형상을 지닙니다. 사각형에 가까운 얼굴로 턱이 넓고 비율이 균형 잡혀 있습니다. 안정과 포용의 기운을 품고 있어 신뢰감 있고 책임감이 강한 성향을 가집니다.",
    faceCharacteristics: [
      "사각형 또는 넓은 얼굴형",
      "넓고 튼튼한 턱",
      "균형 잡힌 이마와 턱 비율",
      "풍성하고 넉넉한 인상",
      "각진 턱선",
    ],
    personalityTraits: [
      "안정적이고 신뢰감 있음",
      "책임감이 강함",
      "포용력이 넓음",
      "실용적이고 현실적",
      "성실하고 끈기 있음",
    ],
    season: "환절기",
    direction: "중앙",
    organ: "비(脾)",
  },
  metal: {
    id: "metal",
    nameKo: "금(金)",
    nameEn: "Metal",
    hanja: "金",
    color: "#a1a1aa",
    bgColor: "bg-zinc-50",
    borderColor: "border-zinc-300",
    description:
      "금(金)형은 금속처럼 정교하고 세련된 형상을 지닙니다. 타원형 얼굴에 광대뼈가 높고 이목구비가 뚜렷합니다. 대칭적이고 정돈된 인상으로 분석력이 뛰어나고 완벽주의적인 성향을 가집니다.",
    faceCharacteristics: [
      "타원형의 균형 잡힌 얼굴",
      "높은 광대뼈",
      "뚜렷하고 정교한 이목구비",
      "높은 좌우 대칭성",
      "세련되고 단정한 인상",
    ],
    personalityTraits: [
      "분석력이 뛰어남",
      "완벽주의적 성향",
      "결단력이 있음",
      "논리적이고 체계적",
      "정의감이 강하고 원칙적",
    ],
    season: "가을",
    direction: "서",
    organ: "폐(肺)",
  },
  water: {
    id: "water",
    nameKo: "수(水)",
    nameEn: "Water",
    hanja: "水",
    color: "#3b82f6",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-300",
    description:
      "수(水)형은 물처럼 부드럽고 유연한 형상을 지닙니다. 둥근 얼굴에 이목구비가 부드럽고 턱이 동그랗습니다. 지혜와 유연성의 기운을 품고 있어 적응력이 뛰어나고 통찰력이 깊은 성향을 가집니다.",
    faceCharacteristics: [
      "둥글고 풍만한 얼굴형",
      "부드러운 이목구비",
      "동그란 턱",
      "풍만하고 부드러운 인상",
      "부드러운 곡선의 턱선",
    ],
    personalityTraits: [
      "지혜롭고 통찰력이 깊음",
      "적응력이 뛰어남",
      "유연하고 융통성 있음",
      "감성이 풍부함",
      "차분하고 침착함",
    ],
    season: "겨울",
    direction: "북",
    organ: "신(腎)",
  },
};

export const ELEMENT_ORDER: ElementType[] = [
  "wood",
  "fire",
  "earth",
  "metal",
  "water",
];
